### ISSUE TITLE
fresh project, followed the directions, failed at npm run dev

### ISSUE THREAD

**Issue by bkinsey808** [johnlindquist/nuxt-typescript-starter#4]
$ npm run dev

> @1.0.1 dev /home/bkinsey/opt/gh/bkinsey808/vue-nuxt-experiment
> nuxt

  nuxt:build App root: /home/bkinsey/opt/gh/bkinsey808/vue-nuxt-experiment +0ms
  nuxt:build Generating .nuxt/ files... +2ms
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:3000
    at Object.exports._errnoException (util.js:1028:11)
    at exports._exceptionWithHostPort (util.js:1051:20)
    at Server._listen2 (net.js:1261:14)
    at listen (net.js:1297:10)
    at doListening (net.js:1396:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:422:7)
    at startup (bootstrap_node.js:143:9)
    at bootstrap_node.js:537:3

**Comment by sebastianmacias** [comment]
Is the port 3000 available before you run npm run dev?

You could make sure it's available by killing the process using the port:

sudo kill $(sudo lsof -t -i:3000)

**Comment by bkinsey808** [comment]
oh yes, how silly of me. Sorry.
